kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - function.yaml
  - runtimeconfig.yaml
  - composition-kcl.yaml

configMapGenerator:
  - name: kcl-templates
    namespace: crossplane-system
    files:
      - javaapp.k=javaapp.k

generatorOptions:
  disableNameSuffixHash: true
